"""routes/courses.py"""
from datetime import datetime
from io import BytesIO
from pathlib import Path
from urllib.parse import parse_qs, urlparse
import json
import re
import sqlite3

from babel.dates import format_date

from flask import Blueprint, current_app, make_response, render_template, redirect, url_for, flash, request, session
from werkzeug.utils import secure_filename

try:
    import arabic_reshaper
    from bidi.algorithm import get_display
    from reportlab.graphics import renderPDF
    from reportlab.graphics.barcode import qr
    from reportlab.graphics.shapes import Drawing
    from reportlab.lib.colors import Color, HexColor
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
    from reportlab.pdfgen import canvas
except ImportError:
    arabic_reshaper = None
    get_display = None
    renderPDF = None
    qr = None
    Drawing = None
    Color = None
    HexColor = None
    A4 = None
    landscape = None
    pdfmetrics = None
    TTFont = None
    canvas = None
from database import fetchone, fetchall, execute, db as db_session
from kechafa_app.core.security import is_admin_like_user
from kechafa_app.services.notification_service import NotificationService
from routes.auth import admin_like_required, instructor_required, login_required

courses_bp = Blueprint("courses", __name__, url_prefix="/courses")
notification_service = NotificationService()
COURSE_DIFFICULTIES = ["beginner", "intermediate", "advanced"]
COURSE_CERTIFICATE_LANGUAGES = ["en", "fr", "ar"]
ALLOWED_LESSON_VIDEO_EXTENSIONS = {"mp4", "mov", "webm", "m4v"}
CERTIFICATE_FONT_NAMES: tuple[str, str] | None = None
CERTIFICATE_COPY = {
    "en": {
        "brand": "ACADEMIC KACHAFA FAKAT",
        "date": "Date",
        "heading": "CERTIFICATE OF COMPLETION",
        "title": "Certificate",
        "presented_to": "This is proudly presented to",
        "completed_course": "for successfully completing the course",
        "recognition": "Awarded in recognition of commitment, achievement, and successful learning progress.",
        "director": "Training Director",
        "signature": "Signature",
        "footer": "Generated by the Academic Kachafa fakat platform",
    },
    "fr": {
        "brand": "ACADEMIC KACHAFA FAKAT",
        "date": "Date",
        "heading": "CERTIFICAT D'ACHEVEMENT",
        "title": "Certificat",
        "presented_to": "Ce certificat est fierement decerne a",
        "completed_course": "pour avoir complete avec succes le cours",
        "recognition": "Attribue en reconnaissance de l'engagement, de la reussite et des progres d'apprentissage accomplis.",
        "director": "Directeur de formation",
        "signature": "Signature",
        "footer": "Genere par la plateforme d'apprentissage Academic Kachafa fakat",
    },
    "ar": {
        "brand": "أكاديمية كشافة فقط",
        "date": "التاريخ",
        "heading": "شهادة إتمام",
        "title": "شهادة",
        "presented_to": "تُمنح هذه الشهادة إلى",
        "completed_course": "لإتمام الدورة بنجاح",
        "recognition": "تقديرًا للالتزام والإنجاز والتقدم الناجح في التعلّم.",
        "director": "مدير التدريب",
        "signature": "التوقيع",
        "footer": "تم إنشاء هذه الشهادة  بواسطة منصة أكاديمية كشافة فقط",
    },
}
ARABIC_MONTH_NAMES = {
    1: "يناير",
    2: "فبراير",
    3: "مارس",
    4: "أبريل",
    5: "مايو",
    6: "يونيو",
    7: "يوليو",
    8: "أغسطس",
    9: "سبتمبر",
    10: "أكتوبر",
    11: "نوفمبر",
    12: "ديسمبر",
}


def _format_completion_date(timestamp: str | None, language: str = "en") -> str:
    if not timestamp:
        date_value = datetime.utcnow().date()
    else:
        try:
            date_value = datetime.strptime(timestamp, "%Y-%m-%d %H:%M:%S").date()
        except ValueError:
            try:
                date_value = datetime.strptime(timestamp[:10], "%Y-%m-%d").date()
            except ValueError:
                return timestamp[:10]
    locale = language if language in COURSE_CERTIFICATE_LANGUAGES else "en"
    if locale == "ar":
        return f"{date_value.day} {ARABIC_MONTH_NAMES[date_value.month]} {date_value.year}"
    try:
        return format_date(date_value, format="long", locale=locale)
    except Exception:
        return date_value.strftime("%B %d, %Y")


def _contains_arabic(text: str | None) -> bool:
    return bool(text and re.search(r"[\u0600-\u06FF]", text))


def _looks_french(text: str | None) -> bool:
    if not text:
        return False
    lowered = text.lower()
    if re.search(r"[àâçéèêëîïôûùüÿœæ]", lowered):
        return True
    padded = f" {lowered} "
    return any(marker in padded for marker in (" le ", " la ", " les ", " des ", " de ", " du ", " pour ", " et "))


def _resolve_course_language(course: dict | None) -> str:
    if not course:
        return "en"
    language = (course.get("language") or "").strip().lower()
    if language in COURSE_CERTIFICATE_LANGUAGES:
        return language
    title = course.get("title", "")
    if _contains_arabic(title):
        return "ar"
    if _looks_french(title):
        return "fr"
    return "en"


def _resolve_course_title_for_certificate(course: dict, language: str) -> str:
    if language == "ar":
        if _contains_arabic(course.get("title")):
            return course.get("title") or ""
        if course.get("title_ar"):
            return course.get("title_ar") or course.get("title") or ""
    return course.get("title") or course.get("title_ar") or ""


def _prepare_certificate_text(text: str, language: str) -> str:
    value = (text or "").strip()
    if language == "ar" and value and arabic_reshaper and get_display:
        return get_display(arabic_reshaper.reshape(value))
    return value


def _find_certificate_font_path(candidates: list[str]) -> str | None:
    for candidate in candidates:
        if Path(candidate).exists():
            return candidate
    return None


def _register_certificate_fonts() -> tuple[str, str]:
    global CERTIFICATE_FONT_NAMES
    if CERTIFICATE_FONT_NAMES:
        return CERTIFICATE_FONT_NAMES

    if not pdfmetrics or not TTFont:
        return ("Helvetica", "Helvetica-Bold")

    regular_path = _find_certificate_font_path([
        "C:/Windows/Fonts/arial.ttf",
        "C:/Windows/Fonts/tahoma.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf",
        "/usr/share/fonts/truetype/noto/NotoNaskhArabic-Regular.ttf",
    ])
    bold_path = _find_certificate_font_path([
        "C:/Windows/Fonts/arialbd.ttf",
        "C:/Windows/Fonts/tahomabd.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/noto/NotoSans-Bold.ttf",
        "/usr/share/fonts/truetype/noto/NotoNaskhArabic-Bold.ttf",
    ])

    regular_name = "Helvetica"
    bold_name = "Helvetica-Bold"
    if regular_path:
        regular_name = "CertificateRegular"
        if regular_name not in pdfmetrics.getRegisteredFontNames():
            pdfmetrics.registerFont(TTFont(regular_name, regular_path))
    if bold_path:
        bold_name = "CertificateBold"
        if bold_name not in pdfmetrics.getRegisteredFontNames():
            pdfmetrics.registerFont(TTFont(bold_name, bold_path))
    elif regular_path:
        bold_name = regular_name

    CERTIFICATE_FONT_NAMES = (regular_name, bold_name)
    return CERTIFICATE_FONT_NAMES


def _wrap_certificate_text(text: str, font_name: str, font_size: float, max_width: float) -> list[str]:
    words = (text or "").split()
    if not words:
        return [""]

    lines: list[str] = []
    current = words[0]
    for word in words[1:]:
        candidate = f"{current} {word}"
        if pdfmetrics.stringWidth(candidate, font_name, font_size) <= max_width:
            current = candidate
        else:
            lines.append(current)
            current = word
    lines.append(current)
    return lines


def _build_course_certificate_pdf(student_name: str, course_title: str, completed_on: str, language: str, qr_payload: str) -> bytes:
    if not all([canvas, landscape, A4, Color, HexColor, pdfmetrics, renderPDF, qr, Drawing]):
        raise RuntimeError("Certificate PDF dependencies are not installed.")

    regular_font, bold_font = _register_certificate_fonts()
    copy = CERTIFICATE_COPY.get(language, CERTIFICATE_COPY["en"])
    raw_completed_on = completed_on
    student_name = _prepare_certificate_text(student_name, language)
    course_title = _prepare_certificate_text(course_title, language)
    completed_on = _prepare_certificate_text(completed_on, language)

    buffer = BytesIO()
    page_width, page_height = landscape(A4)
    pdf = canvas.Canvas(buffer, pagesize=(page_width, page_height), pageCompression=1)

    cream = Color(0.982, 0.975, 0.957)
    gold = HexColor("#d0b265")
    gold_soft = HexColor("#e8d5a9")
    navy = HexColor("#1a2c44")
    slate = HexColor("#6f6255")

    pdf.setFillColor(cream)
    pdf.rect(0, 0, page_width, page_height, fill=1, stroke=0)

    pdf.setStrokeColor(gold)
    pdf.setLineWidth(3.5)
    pdf.rect(24, 24, page_width - 48, page_height - 48, stroke=1, fill=0)

    pdf.setStrokeColor(gold_soft)
    pdf.setLineWidth(1.2)
    pdf.rect(38, 38, page_width - 76, page_height - 76, stroke=1, fill=0)

    # pdf.setFillColor(navy)
    # pdf.rect(58, page_height - 64, page_width - 116, 10, fill=1, stroke=0)
    # pdf.rect(58, 54, page_width - 116, 10, fill=1, stroke=0)

    logo_center_x = page_width - 110 if language == "ar" else 110
    pdf.setFillColor(HexColor("#ffffff"))
    pdf.setStrokeColor(HexColor("#ffffff"))
    pdf.setLineWidth(2.5)
    pdf.circle(logo_center_x, page_height - 104, 28, stroke=1, fill=1)

    logo_path = Path(current_app.static_folder) / "assets" / "logoCerti.png"
    if logo_path.exists():
        logo_size = 100 
        pdf.drawImage(
            str(logo_path),
            logo_center_x - (logo_size / 2),
            (page_height - 104) - (logo_size / 2),
            width=logo_size,
            height=logo_size,
            preserveAspectRatio=True,
            mask="auto",
        )

    pdf.setFillColor(navy)
    pdf.setFont(bold_font, 14)
    brand_label = _prepare_certificate_text(copy["brand"], language)
    if language == "ar":
        pdf.drawRightString(page_width - 155, page_height - 86, brand_label)
    else:
        pdf.drawString(155, page_height - 86, brand_label)

    pdf.setFillColor(slate)
    pdf.setFont(regular_font, 13)
    if language == "ar":
        date_label = _prepare_certificate_text(f"{copy['date']} {raw_completed_on}", language)
        pdf.drawRightString(200, page_height - 86, date_label)
    else:
        date_label = _prepare_certificate_text(f"{copy['date']}: {completed_on}", language)
        date_width = pdfmetrics.stringWidth(date_label, regular_font, 13)
        pdf.drawString(page_width - 72 - date_width, page_height - 86, date_label)

    pdf.setFillColor(gold)
    pdf.setFont(bold_font, 17)
    pdf.drawCentredString(page_width / 2, page_height - 145, _prepare_certificate_text(copy["heading"], language))

    pdf.setFillColor(HexColor("#111111"))
    pdf.setFont(bold_font, 34 if language == "ar" else 36)
    pdf.drawCentredString(page_width / 2, page_height - 198, _prepare_certificate_text(copy["title"], language))

    pdf.setFillColor(slate)
    pdf.setFont(regular_font, 16)
    pdf.drawCentredString(page_width / 2, page_height - 236, _prepare_certificate_text(copy["presented_to"], language))

    pdf.setStrokeColor(gold)
    pdf.setLineWidth(1.2)
    pdf.line(190, page_height - 316, page_width - 190, page_height - 316)
    pdf.line(190, page_height - 245, page_width - 190, page_height - 245)

    pdf.setFillColor(navy)
    pdf.setFont(bold_font, 28 if len(student_name) > 28 else 30)
    pdf.drawCentredString(page_width / 2, page_height - 285, student_name)

    pdf.setFillColor(slate)
    pdf.setFont(regular_font, 16)
    pdf.drawCentredString(page_width / 2, page_height - 344, _prepare_certificate_text(copy["completed_course"], language))

    pdf.setFillColor(gold)
    wrapped_title = _wrap_certificate_text(course_title, bold_font, 24, page_width - 220)
    for index, line in enumerate(wrapped_title[:2]):
        pdf.setFont(bold_font, 24)
        pdf.drawCentredString(page_width / 2, page_height - 394 - (index * 28), line)

    pdf.setFillColor(HexColor("#7a6b57"))
    pdf.setFont(regular_font, 14)
    wrapped_recognition = _wrap_certificate_text(_prepare_certificate_text(copy["recognition"], language), regular_font, 14, page_width - 220)
    for index, line in enumerate(wrapped_recognition[:2]):
        pdf.drawCentredString(page_width / 2, page_height - 442 - (index * 18), line)

    pdf.setStrokeColor(HexColor("#c3a556"))
    pdf.setLineWidth(1)
    pdf.line(132, 144, 300, 144)
    pdf.line(page_width - 300, 144, page_width - 132, 144)

    director_image_path = Path(current_app.static_folder) / "assets" / "asmpt.png"
    if not director_image_path.exists():
        director_image_path = Path(current_app.static_folder) / "assets" / "stamp.png"
    if director_image_path.exists():
        stamp_width = 100
        stamp_height = 100
        director_image_center_x = 200
        pdf.drawImage(
            str(director_image_path),
            director_image_center_x - (stamp_width / 2),
            50,
            width=stamp_width,
            height=stamp_height,
            mask="auto",
            preserveAspectRatio=True,
        )

    pdf.setFillColor(slate)
    pdf.setFont(bold_font, 14)
    pdf.drawCentredString(216, 124, _prepare_certificate_text(copy["director"], language))

    qr_code = qr.QrCodeWidget(qr_payload)
    bounds = qr_code.getBounds()
    qr_size = 70
    qr_width = bounds[2] - bounds[0]
    qr_height = bounds[3] - bounds[1]
    qr_scale_x = qr_size / qr_width
    qr_scale_y = qr_size / qr_height
    qr_drawing = Drawing(
        qr_size,
        qr_size,
        transform=[
            qr_scale_x,
            0,
            0,
            qr_scale_y,
            -bounds[0] * qr_scale_x,
            -bounds[1] * qr_scale_y,
        ],
    )
    qr_drawing.add(qr_code)
    qr_center_x = page_width - 200
    renderPDF.draw(qr_drawing, pdf, qr_center_x - (qr_size / 2), 62)

    pdf.setFont(regular_font, 12)
    pdf.drawCentredString(page_width / 2, 84, _prepare_certificate_text(copy["footer"], language))

    pdf.showPage()
    pdf.save()
    return buffer.getvalue()


def _allowed_lesson_video(filename: str) -> bool:
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_LESSON_VIDEO_EXTENSIONS


def _save_lesson_video(file_storage) -> str:
    filename = secure_filename(file_storage.filename or "")
    if not filename or not _allowed_lesson_video(filename):
        raise ValueError("Please upload a valid video file (.mp4, .mov, .webm, .m4v).")

    uploads_dir = Path(current_app.static_folder) / "uploads" / "content" / "lesson"
    uploads_dir.mkdir(parents=True, exist_ok=True)
    target = uploads_dir / filename

    if target.exists():
        stem = target.stem
        suffix = target.suffix
        counter = 1
        while target.exists():
            target = uploads_dir / f"{stem}_{counter}{suffix}"
            counter += 1

    file_storage.save(target)
    relative_path = target.relative_to(Path(current_app.static_folder)).as_posix()
    return url_for("static", filename=relative_path)


def _delete_local_video_file(video_url: str) -> None:
    static_prefix = url_for("static", filename="")
    if not video_url.startswith(static_prefix):
        return

    relative_path = video_url.replace(static_prefix, "", 1).lstrip("/")
    disk_path = Path(current_app.static_folder) / relative_path
    try:
        if disk_path.exists():
            disk_path.unlink()
    except OSError:
        pass


def _fetch_course_categories(with_counts: bool = False) -> list[dict]:
    if with_counts:
        return fetchall(
            """
            SELECT
                cc.*,
                COUNT(c.id) AS course_count
            FROM course_categories cc
            LEFT JOIN courses c ON c.category = cc.slug
            GROUP BY cc.id
            ORDER BY CASE WHEN cc.slug='general' THEN 1 ELSE 0 END, cc.name COLLATE NOCASE
            """
        )

    return fetchall(
        """
        SELECT *
        FROM course_categories
        ORDER BY CASE WHEN slug='general' THEN 1 ELSE 0 END, name COLLATE NOCASE
        """
    )


def _get_course_category(category_id: int) -> dict | None:
    return fetchone("SELECT * FROM course_categories WHERE id=?", (category_id,))


def _slugify_course_category(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.strip().lower())
    return slug.strip("-") or "general"


def _build_unique_course_category_slug(name: str, current_id: int | None = None) -> str:
    base_slug = _slugify_course_category(name)
    slug = base_slug
    suffix = 2

    while True:
        existing = fetchone("SELECT id FROM course_categories WHERE slug=?", (slug,))
        if not existing or existing["id"] == current_id:
            return slug
        slug = f"{base_slug}-{suffix}"
        suffix += 1


def _course_category_slugs() -> set[str]:
    return {category["slug"] for category in _fetch_course_categories()}


def _get_fallback_course_category(exclude_category_id: int) -> dict | None:
    return fetchone(
        """
        SELECT *
        FROM course_categories
        WHERE id<>?
        ORDER BY CASE WHEN slug='general' THEN 0 ELSE 1 END, name COLLATE NOCASE
        LIMIT 1
        """,
        (exclude_category_id,),
    )


def _current_user_role() -> str | None:
    return (fetchone("SELECT role FROM users WHERE id=?", (session["user_id"],)) or {}).get("role")


def _current_user_record() -> dict | None:
    return fetchone("SELECT * FROM users WHERE id=?", (session["user_id"],))


def _latest_course_access_request(user_id: int, course_id: int) -> dict | None:
    return fetchone(
        """
        SELECT *
        FROM course_access_requests
        WHERE requester_id=? AND course_id=?
        ORDER BY created_at DESC, id DESC
        LIMIT 1
        """,
        (user_id, course_id),
    )


def _notify_enrolled_users_about_lesson(course_id: int, lesson_id: int, title: str, actor_id: int | None) -> None:
    recipients = fetchall("SELECT user_id FROM enrollments WHERE course_id=?", (course_id,))
    for recipient in recipients:
        notification_service.notify_lesson_published(
            recipient_id=recipient["user_id"],
            actor_id=actor_id,
            course_id=course_id,
            lesson_id=lesson_id,
            title=title,
        )


def _can_manage_course(course: dict, user_id: int, role: str | None) -> bool:
    current_user = _current_user_record()
    return is_admin_like_user(current_user) or course["instructor_id"] == user_id


def _lesson_player_meta(video_url: str | None) -> dict:
    if not video_url:
        return {"mode": "video", "embed_url": None}

    parsed = urlparse(video_url)
    host = (parsed.netloc or "").lower()

    if "youtube.com" in host:
        video_id = parse_qs(parsed.query).get("v", [None])[0]
        if video_id:
            return {"mode": "iframe", "embed_url": f"https://www.youtube.com/embed/{video_id}"}
    if "youtu.be" in host:
        video_id = parsed.path.strip("/").split("/")[0] if parsed.path.strip("/") else None
        if video_id:
            return {"mode": "iframe", "embed_url": f"https://www.youtube.com/embed/{video_id}"}
    if "vimeo.com" in host:
        video_id = parsed.path.strip("/").split("/")[0] if parsed.path.strip("/") else None
        if video_id and video_id.isdigit():
            return {"mode": "iframe", "embed_url": f"https://player.vimeo.com/video/{video_id}"}

    return {"mode": "video", "embed_url": None}


def _empty_quiz_question() -> dict:
    return {
        "quiz_question": "",
        "quiz_option_a": "",
        "quiz_option_b": "",
        "quiz_option_c": "",
        "quiz_option_d": "",
        "quiz_correct_option": "",
        "quiz_explanation": "",
    }


def _legacy_quiz_payload_from_lesson(lesson: dict | None) -> dict | None:
    if not lesson:
        return None

    quiz = {
        "quiz_question": (lesson.get("quiz_question") or "").strip(),
        "quiz_option_a": (lesson.get("quiz_option_a") or "").strip(),
        "quiz_option_b": (lesson.get("quiz_option_b") or "").strip(),
        "quiz_option_c": (lesson.get("quiz_option_c") or "").strip(),
        "quiz_option_d": (lesson.get("quiz_option_d") or "").strip(),
        "quiz_correct_option": (lesson.get("quiz_correct_option") or "").strip().lower(),
        "quiz_explanation": (lesson.get("quiz_explanation") or "").strip(),
    }
    return quiz if any(quiz.values()) else None


def _quiz_payloads_from_form(form, include_blank: bool = False) -> list[dict]:
    fields = {
        "quiz_question": form.getlist("quiz_question[]"),
        "quiz_option_a": form.getlist("quiz_option_a[]"),
        "quiz_option_b": form.getlist("quiz_option_b[]"),
        "quiz_option_c": form.getlist("quiz_option_c[]"),
        "quiz_option_d": form.getlist("quiz_option_d[]"),
        "quiz_correct_option": form.getlist("quiz_correct_option[]"),
        "quiz_explanation": form.getlist("quiz_explanation[]"),
    }
    total = max((len(values) for values in fields.values()), default=0)
    quizzes: list[dict] = []

    for index in range(total):
        quiz = {
            key: (values[index].strip() if index < len(values) else "")
            for key, values in fields.items()
        }
        quiz["quiz_correct_option"] = quiz["quiz_correct_option"].lower()
        if include_blank or any(quiz.values()):
            quizzes.append(quiz)

    return quizzes


def _validate_quiz_payload(quiz: dict) -> list[str]:
    if not any(quiz.values()):
        return []

    errors = []
    if not quiz["quiz_question"]:
        errors.append("Quiz question is required when adding a quiz.")
    if not quiz["quiz_option_a"] or not quiz["quiz_option_b"]:
        errors.append("Quiz options A and B are required when adding a quiz.")

    available_options = {
        key for key, text in {
            "a": quiz["quiz_option_a"],
            "b": quiz["quiz_option_b"],
            "c": quiz["quiz_option_c"],
            "d": quiz["quiz_option_d"],
        }.items() if text
    }
    if quiz["quiz_correct_option"] not in available_options:
        errors.append("Select a correct answer from the filled quiz options.")

    return errors


def _validate_quiz_payloads(quizzes: list[dict]) -> list[str]:
    errors: list[str] = []
    for index, quiz in enumerate(quizzes, start=1):
        for error in _validate_quiz_payload(quiz):
            errors.append(f"Quiz question {index}: {error}")
    return errors


def _fetch_lesson_quiz_questions(lesson_id: int, lesson: dict | None = None) -> list[dict]:
    quizzes = [
        {
            "id": row["id"],
            "quiz_question": row["question_text"],
            "quiz_option_a": row["option_a"],
            "quiz_option_b": row["option_b"],
            "quiz_option_c": row["option_c"] or "",
            "quiz_option_d": row["option_d"] or "",
            "quiz_correct_option": (row["correct_option"] or "").lower(),
            "quiz_explanation": row["explanation"] or "",
            "order_index": row["order_index"],
        }
        for row in fetchall(
            """
            SELECT id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, order_index
            FROM lesson_quiz_questions
            WHERE lesson_id=?
            ORDER BY order_index ASC, id ASC
            """,
            (lesson_id,),
        )
    ]
    if quizzes:
        return quizzes

    legacy_quiz = _legacy_quiz_payload_from_lesson(lesson)
    if legacy_quiz:
        legacy_quiz["id"] = None
        legacy_quiz["order_index"] = 1
        return [legacy_quiz]
    return []


def _lesson_form_data_from_request(form, default_order: int) -> dict:
    quiz_questions = _quiz_payloads_from_form(form, include_blank=True)
    return {
        "title": form.get("title", "").strip(),
        "description": form.get("description", "").strip(),
        "video_url": form.get("video_url", "").strip(),
        "thumbnail_url": form.get("thumbnail_url", "").strip(),
        "duration_secs": form.get("duration_secs", 300),
        "order_index": form.get("order_index", default_order),
        "xp_reward": form.get("xp_reward", 50),
        "is_published": "1" if form.get("is_published") else "",
        "video_source": form.get("video_source", "link"),
        "quiz_questions": quiz_questions or [_empty_quiz_question()],
    }


def _lesson_form_data_from_lesson(lesson: dict, quiz_questions: list[dict]) -> dict:
    return {
        "title": lesson.get("title", ""),
        "description": lesson.get("description", ""),
        "video_url": lesson.get("video_url", ""),
        "thumbnail_url": lesson.get("thumbnail_url", ""),
        "duration_secs": lesson.get("duration_secs", 300),
        "order_index": lesson.get("order_index", 1),
        "xp_reward": lesson.get("xp_reward", 50),
        "is_published": "1" if lesson.get("is_published") else "",
        "video_source": "link",
        "quiz_questions": quiz_questions or [_empty_quiz_question()],
    }


def _primary_quiz_payload(quizzes: list[dict]) -> dict:
    return quizzes[0] if quizzes else _empty_quiz_question()


def _replace_lesson_quiz_questions(conn: sqlite3.Connection, lesson_id: int, quizzes: list[dict]) -> None:
    conn.execute("DELETE FROM lesson_quiz_questions WHERE lesson_id=?", (lesson_id,))
    for index, quiz in enumerate(quizzes, start=1):
        conn.execute(
            """
            INSERT INTO lesson_quiz_questions
                (lesson_id, question_text, option_a, option_b, option_c, option_d, correct_option, explanation, order_index)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                lesson_id,
                quiz["quiz_question"],
                quiz["quiz_option_a"],
                quiz["quiz_option_b"],
                quiz["quiz_option_c"] or None,
                quiz["quiz_option_d"] or None,
                quiz["quiz_correct_option"],
                quiz["quiz_explanation"] or None,
                index,
            ),
        )


def _mark_lesson_complete(user_id: int, course_id: int, video_id: int, quiz_answer: str | None = None, quiz_score: float = 0.0) -> dict:
    enrollment = fetchone("SELECT * FROM enrollments WHERE user_id=? AND course_id=?", (user_id, course_id))
    if not enrollment:
        return {"ok": False, "reason": "not_enrolled"}

    video = fetchone("SELECT * FROM videos WHERE id=? AND course_id=? AND video_type='lesson'", (video_id, course_id))
    if not video:
        return {"ok": False, "reason": "lesson_not_found"}

    existing = fetchone("SELECT id FROM lesson_completions WHERE user_id=? AND video_id=?", (user_id, video_id))
    if existing:
        return {"ok": True, "already_completed": True, "course_completed": bool(enrollment.get("is_completed"))}

    execute(
        "INSERT INTO lesson_completions (user_id, course_id, video_id, quiz_answer, quiz_score) VALUES (?,?,?,?,?)",
        (user_id, course_id, video_id, quiz_answer, quiz_score),
    )
    execute("UPDATE users SET level_points=level_points+? WHERE id=?", (video.get("xp_reward", 0), user_id))

    lesson_total = (fetchone(
        "SELECT COUNT(*) as c FROM videos WHERE course_id=? AND video_type='lesson'",
        (course_id,),
    ) or {}).get("c", 1)
    completed_total = (fetchone(
        "SELECT COUNT(*) as c FROM lesson_completions WHERE user_id=? AND course_id=?",
        (user_id, course_id),
    ) or {}).get("c", 0)

    progress_pct = min(100.0, (completed_total * 100.0) / max(1, lesson_total))
    course_completed_now = progress_pct >= 100 and not enrollment.get("is_completed")

    if course_completed_now:
        course = fetchone("SELECT xp_reward FROM courses WHERE id=?", (course_id,)) or {}
        execute("UPDATE users SET level_points=level_points+? WHERE id=?", (course.get("xp_reward", 0), user_id))
        execute(
            "UPDATE enrollments SET progress_pct=?, is_completed=1, completed_at=datetime('now') WHERE user_id=? AND course_id=?",
            (progress_pct, user_id, course_id),
        )
    else:
        execute(
            "UPDATE enrollments SET progress_pct=? WHERE user_id=? AND course_id=?",
            (progress_pct, user_id, course_id),
        )

    execute("UPDATE users SET level_rank=MAX(1, level_points / 1000) WHERE id=?", (user_id,))
    return {"ok": True, "already_completed": False, "course_completed": course_completed_now}


@courses_bp.route("/")
@login_required
def index():
    uid = session["user_id"]
    current_user = fetchone("SELECT id, role, username FROM users WHERE id=?", (uid,)) or {}
    category = request.args.get("category", "all")
    difficulty = request.args.get("difficulty", "all")
    categories = _fetch_course_categories(with_counts=True)
    page = max(1, request.args.get("page", 1, type=int))
    per_page = 9
    offset = (page - 1) * per_page

    wheres, params = ["c.is_published=1"], []
    if is_admin_like_user(current_user):
        wheres = ["1=1"]
    elif current_user.get("role") == "instructor":
        wheres = ["(c.is_published=1 OR c.instructor_id=?)"]
        params.append(uid)
    if category != "all":
        wheres.append("c.category=?")
        params.append(category)
    if difficulty != "all":
        wheres.append("c.difficulty=?")
        params.append(difficulty)
    where_sql = " AND ".join(wheres)

    total = (fetchone(f"SELECT COUNT(*) as cnt FROM courses c WHERE {where_sql}", tuple(params)) or {}).get("cnt", 0)
    courses = fetchall(
        f"SELECT c.*, cc.name as category_name, cc.emoji as category_emoji, u.full_name, u.avatar_url as uavatar, "
        f"(SELECT COUNT(*) FROM enrollments WHERE course_id=c.id) as enrolled_count "
        f"FROM courses c JOIN users u ON c.instructor_id=u.id "
        f"LEFT JOIN course_categories cc ON cc.slug = c.category "
        f"WHERE {where_sql} ORDER BY c.is_featured DESC, c.created_at DESC "
        f"LIMIT ? OFFSET ?",
        tuple(params) + (per_page, offset),
    )

    enrolled_ids = {r["course_id"] for r in fetchall("SELECT course_id FROM enrollments WHERE user_id=?", (uid,))}
    total_pages = max(1, (total + per_page - 1) // per_page)
    return render_template(
        "courses/index.html",
        courses=courses,
        categories=categories,
        enrolled_ids=enrolled_ids,
        active_category=category,
        active_difficulty=difficulty,
        page=page,
        total_pages=total_pages,
        has_prev=(page > 1),
        has_next=(page < total_pages),
        prev_num=page - 1,
        next_num=page + 1,
    )


@courses_bp.route("/add", methods=["GET", "POST"])
@instructor_required
def add():
    categories = _fetch_course_categories()
    form_data = request.form if request.method == "POST" else {"is_published": "1", "language": session.get("lang", "en")}

    if request.method == "POST":
        title = request.form.get("title", "").strip()
        description = request.form.get("description", "").strip()
        thumbnail_url = request.form.get("thumbnail_url", "").strip()
        language = request.form.get("language", session.get("lang", "en")).strip().lower()
        category = request.form.get("category", "general")
        difficulty = request.form.get("difficulty", "beginner")
        xp_reward = request.form.get("xp_reward", 500, type=int)
        duration_mins = request.form.get("duration_mins", 0, type=int)
        is_published = 1 if request.form.get("is_published") else 0
        is_featured = 1 if request.form.get("is_featured") else 0
        valid_categories = _course_category_slugs()

        errors = []
        if not title:
            errors.append("Course title is required.")
        if language not in COURSE_CERTIFICATE_LANGUAGES:
            errors.append("Choose a valid certificate language.")
        if category not in valid_categories:
            errors.append("Invalid category selected.")
        if difficulty not in COURSE_DIFFICULTIES:
            errors.append("Invalid difficulty selected.")
        if xp_reward < 0:
            errors.append("XP reward must be positive.")
        if duration_mins < 0:
            errors.append("Duration must be positive.")

        if errors:
            for error in errors:
                flash(error, "danger")
            return render_template("courses/add.html", form_data=form_data, categories=categories, difficulties=COURSE_DIFFICULTIES)

        course_id = execute(
            "INSERT INTO courses (title,description,thumbnail_url,language,category,difficulty,xp_reward,duration_mins,is_published,is_featured,instructor_id) VALUES (?,?,?,?,?,?,?,?,?,?,?)",
            (
                title,
                description,
                thumbnail_url,
                language,
                category,
                difficulty,
                xp_reward,
                duration_mins,
                is_published,
                is_featured,
                session["user_id"],
            ),
        )
        if is_published:
            notification_service.notify_course_published(
                instructor_id=session["user_id"],
                course_id=course_id,
                title=title,
            )
        flash("Course created successfully.", "success")
        return redirect(url_for("courses.add_lesson", course_id=course_id))

    return render_template("courses/add.html", form_data=form_data, categories=categories, difficulties=COURSE_DIFFICULTIES)


@courses_bp.route("/<int:course_id>/edit", methods=["GET", "POST"])
@instructor_required
def edit(course_id):
    course = fetchone("SELECT * FROM courses WHERE id=?", (course_id,))
    categories = _fetch_course_categories()
    if not course:
        flash("Course not found.", "danger")
        return redirect(url_for("courses.index"))

    user_id = session["user_id"]
    role = _current_user_role()
    if not _can_manage_course(course, user_id, role):
        flash("You can only edit your own courses.", "danger")
        return redirect(url_for("courses.index"))

    form_data = request.form if request.method == "POST" else {
        "title": course.get("title", ""),
        "description": course.get("description", ""),
        "thumbnail_url": course.get("thumbnail_url", ""),
        "language": course.get("language", "en"),
        "category": course.get("category", "general"),
        "difficulty": course.get("difficulty", "beginner"),
        "xp_reward": course.get("xp_reward", 500),
        "duration_mins": course.get("duration_mins", 60),
        "is_published": "1" if course.get("is_published") else "",
        "is_featured": "1" if course.get("is_featured") else "",
    }

    if request.method == "POST":
        title = request.form.get("title", "").strip()
        description = request.form.get("description", "").strip()
        thumbnail_url = request.form.get("thumbnail_url", "").strip()
        language = request.form.get("language", course.get("language", "en")).strip().lower()
        category = request.form.get("category", "general")
        difficulty = request.form.get("difficulty", "beginner")
        xp_reward = request.form.get("xp_reward", 500, type=int)
        duration_mins = request.form.get("duration_mins", 0, type=int)
        is_published = 1 if request.form.get("is_published") else 0
        is_featured = 1 if request.form.get("is_featured") else 0
        valid_categories = _course_category_slugs()

        errors = []
        if not title:
            errors.append("Course title is required.")
        if language not in COURSE_CERTIFICATE_LANGUAGES:
            errors.append("Choose a valid certificate language.")
        if category not in valid_categories:
            errors.append("Invalid category selected.")
        if difficulty not in COURSE_DIFFICULTIES:
            errors.append("Invalid difficulty selected.")
        if xp_reward < 0:
            errors.append("XP reward must be positive.")
        if duration_mins < 0:
            errors.append("Duration must be positive.")

        if errors:
            for error in errors:
                flash(error, "danger")
            return render_template(
                "courses/add.html",
                form_data=form_data,
                categories=categories,
                difficulties=COURSE_DIFFICULTIES,
                is_edit=True,
                course=course,
            )

        execute(
            "UPDATE courses SET title=?, description=?, thumbnail_url=?, language=?, category=?, difficulty=?, xp_reward=?, duration_mins=?, is_published=?, is_featured=? WHERE id=?",
            (
                title,
                description,
                thumbnail_url,
                language,
                category,
                difficulty,
                xp_reward,
                duration_mins,
                is_published,
                is_featured,
                course_id,
            ),
        )
        if course.get("category") != category:
            execute("UPDATE videos SET category=? WHERE course_id=?", (category, course_id))
        if is_published and not course.get("is_published"):
            notification_service.notify_course_published(
                instructor_id=session["user_id"],
                course_id=course_id,
                title=title,
            )
        flash("Course updated successfully.", "success")
        return redirect(url_for("courses.detail", course_id=course_id))

    return render_template(
        "courses/add.html",
        form_data=form_data,
        categories=categories,
        difficulties=COURSE_DIFFICULTIES,
        is_edit=True,
        course=course,
    )


@courses_bp.route("/categories", methods=["GET", "POST"])
@admin_like_required
def manage_categories():
    if request.method == "POST":
        name = request.form.get("name", "").strip()
        description = request.form.get("description", "").strip()
        emoji = request.form.get("emoji", "").strip() or "📚"

        if not name:
            flash("Category name is required.", "danger")
            return redirect(url_for("courses.manage_categories"))

        existing = fetchone("SELECT id FROM course_categories WHERE lower(name)=lower(?)", (name,))
        if existing:
            flash("Category already exists.", "danger")
            return redirect(url_for("courses.manage_categories"))

        execute(
            "INSERT INTO course_categories (name, slug, description, emoji, created_by) VALUES (?, ?, ?, ?, ?)",
            (name, _build_unique_course_category_slug(name), description, emoji, session["user_id"]),
        )
        flash("Course category added successfully.", "success")
        return redirect(url_for("courses.manage_categories"))

    categories = _fetch_course_categories(with_counts=True)
    return render_template("courses/categories.html", categories=categories)


@courses_bp.route("/categories/<int:category_id>/edit", methods=["GET", "POST"])
@admin_like_required
def edit_category(category_id: int):
    category = _get_course_category(category_id)
    if not category:
        flash("Course category not found.", "danger")
        return redirect(url_for("courses.manage_categories"))

    if request.method == "POST":
        name = request.form.get("name", "").strip()
        description = request.form.get("description", "").strip()
        emoji = request.form.get("emoji", "").strip() or "📚"

        if not name:
            flash("Category name is required.", "danger")
            return redirect(url_for("courses.edit_category", category_id=category_id))

        existing = fetchone(
            "SELECT id FROM course_categories WHERE lower(name)=lower(?) AND id<>?",
            (name, category_id),
        )
        if existing:
            flash("Category already exists.", "danger")
            return redirect(url_for("courses.edit_category", category_id=category_id))

        new_slug = _build_unique_course_category_slug(name, current_id=category_id)
        old_slug = category["slug"]
        execute(
            "UPDATE course_categories SET name=?, slug=?, description=?, emoji=? WHERE id=?",
            (name, new_slug, description, emoji, category_id),
        )
        if old_slug != new_slug:
            execute("UPDATE courses SET category=? WHERE category=?", (new_slug, old_slug))
            execute("UPDATE videos SET category=? WHERE course_id IS NOT NULL AND category=?", (new_slug, old_slug))

        flash("Course category updated successfully.", "success")
        return redirect(url_for("courses.manage_categories"))

    return render_template("courses/category_form.html", category=category)


@courses_bp.route("/categories/<int:category_id>/delete", methods=["POST"])
@admin_like_required
def delete_category(category_id: int):
    category = _get_course_category(category_id)
    if not category:
        flash("Course category not found.", "danger")
        return redirect(url_for("courses.manage_categories"))

    categories_count = fetchone("SELECT COUNT(*) AS c FROM course_categories")
    if categories_count and categories_count["c"] <= 1:
        flash("At least one course category is required.", "danger")
        return redirect(url_for("courses.manage_categories"))

    fallback = _get_fallback_course_category(category_id)
    if not fallback:
        flash("At least one course category is required.", "danger")
        return redirect(url_for("courses.manage_categories"))

    courses_count = fetchone("SELECT COUNT(*) AS c FROM courses WHERE category=?", (category["slug"],))

    try:
        with db_session() as conn:
            if courses_count and courses_count["c"] > 0:
                conn.execute(
                    "UPDATE courses SET category=? WHERE category=?",
                    (fallback["slug"], category["slug"]),
                )

            conn.execute("DELETE FROM course_categories WHERE id=?", (category_id,))
    except sqlite3.IntegrityError:
        flash("This category is still linked to other course data and could not be removed.", "danger")
        return redirect(url_for("courses.manage_categories"))

    if courses_count and courses_count["c"] > 0:
        flash(
            f"Course category deleted successfully. Courses were moved to {fallback['name']}.",
            "success",
        )
    else:
        flash("Course category deleted successfully.", "success")
    return redirect(url_for("courses.manage_categories"))


@courses_bp.route("/<int:course_id>/lessons/add", methods=["GET", "POST"])
@instructor_required
def add_lesson(course_id):
    course = fetchone("SELECT * FROM courses WHERE id=?", (course_id,))
    if not course:
        flash("Course not found.", "danger")
        return redirect(url_for("courses.index"))

    user_id = session["user_id"]
    role = _current_user_role()
    if not _can_manage_course(course, user_id, role):
        flash("You can only manage lessons in your own courses.", "danger")
        return redirect(url_for("courses.index"))

    lesson_count = (fetchone(
        "SELECT COUNT(*) as c FROM videos WHERE course_id=? AND video_type='lesson'",
        (course_id,),
    ) or {}).get("c", 0)
    next_order = (fetchone(
        "SELECT COALESCE(MAX(order_index), 0) + 1 as next_order FROM videos WHERE course_id=? AND video_type='lesson'",
        (course_id,),
    ) or {}).get("next_order", 1)
    form_data = _lesson_form_data_from_request(request.form, next_order) if request.method == "POST" else {
        "duration_secs": 300,
        "order_index": next_order,
        "xp_reward": 50,
        "is_published": "1",
        "video_source": "link",
        "quiz_questions": [_empty_quiz_question()],
    }
    if request.method == "POST":
        video_source = request.form.get("video_source", "link")
        title = request.form.get("title", "").strip()
        description = request.form.get("description", "").strip()
        video_url = request.form.get("video_url", "").strip()
        video_file = request.files.get("video_file")
        thumbnail_url = request.form.get("thumbnail_url", "").strip()
        duration_secs = request.form.get("duration_secs", 0, type=int)
        order_index = request.form.get("order_index", 0, type=int)
        xp_reward = request.form.get("xp_reward", 50, type=int)
        is_published = 1 if request.form.get("is_published") else 0
        quizzes = _quiz_payloads_from_form(request.form)

        errors = []
        if not title:
            errors.append("Lesson title is required.")
        if video_source not in {"link", "upload"}:
            errors.append("Choose a valid video source.")
        if video_source == "link" and not video_url:
            errors.append("Video URL is required.")
        if video_source == "upload":
            if not video_file or not video_file.filename:
                errors.append("Please choose a video file to upload.")
            elif not _allowed_lesson_video(video_file.filename):
                errors.append("Please upload a valid video file (.mp4, .mov, .webm, .m4v).")
        if duration_secs < 0:
            errors.append("Duration must be positive.")
        if order_index < 0:
            errors.append("Order index must be positive.")
        errors.extend(_validate_quiz_payloads(quizzes))

        if errors:
            for e in errors:
                flash(e, "danger")
            return render_template(
                "courses/add_lesson.html",
                course=course,
                form_data=form_data,
                lesson_count=lesson_count,
                next_order=next_order,
            )

        final_video_url = video_url
        if video_source == "upload":
            try:
                final_video_url = _save_lesson_video(video_file)
            except ValueError as exc:
                flash(str(exc), "danger")
                return render_template(
                    "courses/add_lesson.html",
                    course=course,
                    form_data=form_data,
                    lesson_count=lesson_count,
                    next_order=next_order,
                )

        primary_quiz = _primary_quiz_payload(quizzes)
        with db_session() as conn:
            cursor = conn.execute(
                "INSERT INTO videos (title, description, video_url, thumbnail_url, video_type, category, duration_secs, order_index, xp_reward, is_published, uploader_id, course_id, quiz_question, quiz_option_a, quiz_option_b, quiz_option_c, quiz_option_d, quiz_correct_option, quiz_explanation) "
                "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                (
                    title,
                    description,
                    final_video_url,
                    thumbnail_url,
                    "lesson",
                    course.get("category", "general"),
                    duration_secs,
                    order_index,
                    xp_reward,
                    is_published,
                    user_id,
                    course_id,
                    primary_quiz["quiz_question"] or None,
                    primary_quiz["quiz_option_a"] or None,
                    primary_quiz["quiz_option_b"] or None,
                    primary_quiz["quiz_option_c"] or None,
                    primary_quiz["quiz_option_d"] or None,
                    primary_quiz["quiz_correct_option"] or None,
                    primary_quiz["quiz_explanation"] or None,
                ),
            )
            lesson_id = cursor.lastrowid
            _replace_lesson_quiz_questions(conn, lesson_id, quizzes)
        if is_published and course.get("is_published"):
            _notify_enrolled_users_about_lesson(course_id, lesson_id, title, user_id)
        flash("Lesson added to course.", "success")
        if request.form.get("add_another"):
            return redirect(url_for("courses.add_lesson", course_id=course_id))
        return redirect(url_for("courses.detail", course_id=course_id))

    return render_template(
        "courses/add_lesson.html",
        course=course,
        form_data=form_data,
        lesson_count=lesson_count,
        next_order=next_order,
    )


@courses_bp.route("/<int:course_id>/lesson/<int:video_id>/edit", methods=["GET", "POST"])
@instructor_required
def edit_lesson(course_id, video_id):
    course = fetchone("SELECT * FROM courses WHERE id=?", (course_id,))
    if not course:
        flash("Course not found.", "danger")
        return redirect(url_for("courses.index"))

    user_id = session["user_id"]
    role = _current_user_role()
    if not _can_manage_course(course, user_id, role):
        flash("You can only manage lessons in your own courses.", "danger")
        return redirect(url_for("courses.index"))

    lesson = fetchone("SELECT * FROM videos WHERE id=? AND course_id=? AND video_type='lesson'", (video_id, course_id))
    if not lesson:
        flash("Lesson not found.", "danger")
        return redirect(url_for("courses.detail", course_id=course_id))

    lesson_count = (fetchone(
        "SELECT COUNT(*) as c FROM videos WHERE course_id=? AND video_type='lesson'",
        (course_id,),
    ) or {}).get("c", 0)
    existing_quizzes = _fetch_lesson_quiz_questions(video_id, lesson)
    form_data = (
        _lesson_form_data_from_request(request.form, lesson.get("order_index", 1))
        if request.method == "POST"
        else _lesson_form_data_from_lesson(lesson, existing_quizzes)
    )

    if request.method == "POST":
        video_source = request.form.get("video_source", "link")
        title = request.form.get("title", "").strip()
        description = request.form.get("description", "").strip()
        video_url = request.form.get("video_url", "").strip()
        video_file = request.files.get("video_file")
        thumbnail_url = request.form.get("thumbnail_url", "").strip()
        duration_secs = request.form.get("duration_secs", 0, type=int)
        order_index = request.form.get("order_index", 0, type=int)
        xp_reward = request.form.get("xp_reward", 50, type=int)
        is_published = 1 if request.form.get("is_published") else 0
        quizzes = _quiz_payloads_from_form(request.form)

        errors = []
        if not title:
            errors.append("Lesson title is required.")
        if video_source not in {"link", "upload"}:
            errors.append("Choose a valid video source.")
        if video_source == "link" and not video_url:
            errors.append("Video URL is required.")
        if video_source == "upload" and video_file and video_file.filename and not _allowed_lesson_video(video_file.filename):
            errors.append("Please upload a valid video file (.mp4, .mov, .webm, .m4v).")
        if duration_secs < 0:
            errors.append("Duration must be positive.")
        if order_index < 0:
            errors.append("Order index must be positive.")
        errors.extend(_validate_quiz_payloads(quizzes))

        if errors:
            for error in errors:
                flash(error, "danger")
            return render_template(
                "courses/add_lesson.html",
                course=course,
                lesson=lesson,
                form_data=form_data,
                lesson_count=lesson_count,
                next_order=lesson.get("order_index", 1),
                is_edit=True,
            )

        final_video_url = lesson["video_url"]
        if video_source == "link":
            final_video_url = video_url
        elif video_file and video_file.filename:
            try:
                final_video_url = _save_lesson_video(video_file)
            except ValueError as exc:
                flash(str(exc), "danger")
                return render_template(
                    "courses/add_lesson.html",
                    course=course,
                    lesson=lesson,
                    form_data=form_data,
                    lesson_count=lesson_count,
                    next_order=lesson.get("order_index", 1),
                    is_edit=True,
                )

        primary_quiz = _primary_quiz_payload(quizzes)
        with db_session() as conn:
            conn.execute(
                "UPDATE videos SET title=?, description=?, video_url=?, thumbnail_url=?, duration_secs=?, order_index=?, xp_reward=?, is_published=?, quiz_question=?, quiz_option_a=?, quiz_option_b=?, quiz_option_c=?, quiz_option_d=?, quiz_correct_option=?, quiz_explanation=? WHERE id=? AND course_id=?",
                (
                    title,
                    description,
                    final_video_url,
                    thumbnail_url,
                    duration_secs,
                    order_index,
                    xp_reward,
                    is_published,
                    primary_quiz["quiz_question"] or None,
                    primary_quiz["quiz_option_a"] or None,
                    primary_quiz["quiz_option_b"] or None,
                    primary_quiz["quiz_option_c"] or None,
                    primary_quiz["quiz_option_d"] or None,
                    primary_quiz["quiz_correct_option"] or None,
                    primary_quiz["quiz_explanation"] or None,
                    video_id,
                    course_id,
                ),
            )
            _replace_lesson_quiz_questions(conn, video_id, quizzes)
        if is_published and not lesson.get("is_published") and course.get("is_published"):
            _notify_enrolled_users_about_lesson(course_id, video_id, title, user_id)

        if lesson.get("video_url") and lesson["video_url"] != final_video_url:
            _delete_local_video_file(lesson["video_url"])

        flash("Lesson updated successfully.", "success")
        return redirect(url_for("courses.detail", course_id=course_id))

    return render_template(
        "courses/add_lesson.html",
        course=course,
        lesson=lesson,
        form_data=form_data,
        lesson_count=lesson_count,
        next_order=lesson.get("order_index", 1),
        is_edit=True,
    )


@courses_bp.route("/<int:course_id>/enroll-user", methods=["POST"])
@instructor_required
def enroll_user_admin(course_id):
    course = fetchone("SELECT * FROM courses WHERE id=?", (course_id,))
    if not course:
        flash("Course not found.", "danger")
        return redirect(url_for("courses.index"))

    user_id = session["user_id"]
    role = _current_user_role()
    if not _can_manage_course(course, user_id, role):
        flash("You can only manage enrollment in your own courses.", "danger")
        return redirect(url_for("courses.index"))

    identifier = request.form.get("user_identifier", "").strip()
    if not identifier:
        flash("Please provide a username or email.", "warning")
        return redirect(url_for("courses.detail", course_id=course_id))

    user = fetchone("SELECT * FROM users WHERE username=? OR email=?", (identifier, identifier))
    if not user:
        flash("User not found.", "danger")
        return redirect(url_for("courses.detail", course_id=course_id))

    existing = fetchone("SELECT id FROM enrollments WHERE user_id=? AND course_id=?", (user["id"], course_id))
    if not existing:
        execute("INSERT INTO enrollments (user_id,course_id) VALUES (?,?)", (user["id"], course_id))
        notification_service.notify_course_access(
            user_id=user["id"],
            course=course,
            actor_id=session["user_id"],
            title_prefix="Admin enrolled you in",
        )
        flash(f"User '{identifier}' enrolled.", "success")
    else:
        flash("User already enrolled.", "info")

    return redirect(url_for("courses.detail", course_id=course_id))


@courses_bp.route("/<int:course_id>/delete", methods=["POST"])
@instructor_required
def delete(course_id):
    course = fetchone("SELECT * FROM courses WHERE id=?", (course_id,))
    if not course:
        flash("Course not found.", "danger")
        return redirect(url_for("courses.index"))

    current_user_id = session["user_id"]
    current_user = fetchone("SELECT id, role, username FROM users WHERE id=?", (current_user_id,)) or {}
    if not is_admin_like_user(current_user) and course["instructor_id"] != current_user_id:
        flash("You can only delete your own courses.", "danger")
        return redirect(url_for("courses.index"))

    lesson_videos = fetchall("SELECT video_url FROM videos WHERE course_id=?", (course_id,))
    with db_session() as conn:
        conn.execute(
            "DELETE FROM comments WHERE video_id IN (SELECT id FROM videos WHERE course_id=?)",
            (course_id,),
        )
        conn.execute(
            "DELETE FROM likes WHERE video_id IN (SELECT id FROM videos WHERE course_id=?)",
            (course_id,),
        )
        conn.execute("DELETE FROM videos WHERE course_id=?", (course_id,))
        conn.execute("DELETE FROM enrollments WHERE course_id=?", (course_id,))
        conn.execute("DELETE FROM courses WHERE id=?", (course_id,))

    for lesson_video in lesson_videos:
        if lesson_video.get("video_url"):
            _delete_local_video_file(lesson_video["video_url"])

    flash(f"Course '{course['title']}' deleted.", "success")
    return redirect(url_for("courses.index"))


@courses_bp.route("/<int:course_id>")
@login_required
def detail(course_id):
    uid = session["user_id"]
    role = _current_user_role()
    notification_service.mark_related_as_read(uid, entity_type="course", entity_id=course_id)
    course = fetchone(
        "SELECT c.*, cc.name as category_name, cc.emoji as category_emoji, u.full_name, u.avatar_url as uavatar, u.level_rank, "
        "(SELECT COUNT(*) FROM enrollments WHERE course_id=c.id) as enrolled_count "
        "FROM courses c JOIN users u ON c.instructor_id=u.id "
        "LEFT JOIN course_categories cc ON cc.slug = c.category "
        "WHERE c.id=?",
        (course_id,),
    )
    if not course:
        flash("Course not found.", "danger")
        return redirect(url_for("courses.index"))
    enrollment = fetchone("SELECT * FROM enrollments WHERE user_id=? AND course_id=?", (uid, course_id))
    access_request = _latest_course_access_request(uid, course_id)
    can_manage = _can_manage_course(course, uid, role)
    lessons = fetchall(
        "SELECT * FROM videos WHERE course_id=? AND video_type='lesson' "
        + ("" if can_manage else "AND is_published=1 ")
        + "ORDER BY order_index ASC",
        (course_id,),
    )
    completed_ids = {
        row["video_id"] for row in fetchall(
            "SELECT video_id FROM lesson_completions WHERE user_id=? AND course_id=?",
            (uid, course_id),
        )
    }
    selected_lesson_id = request.args.get("lesson_id", type=int)

    def dur_fmt(seconds):
        if not seconds:
            return "-"
        minutes, sec = divmod(int(seconds), 60)
        return f"{minutes}:{sec:02d}"

    selected_lesson = None
    for lesson in lessons:
        lesson["duration_display"] = dur_fmt(lesson.get("duration_secs"))
        lesson["is_completed"] = lesson["id"] in completed_ids
        if selected_lesson_id and lesson["id"] == selected_lesson_id:
            selected_lesson = lesson

    if not selected_lesson and lessons:
        selected_lesson = lessons[0]

    if selected_lesson:
        selected_lesson.update(_lesson_player_meta(selected_lesson.get("video_url")))

    return render_template(
        "courses/detail.html",
        course=course,
        enrollment=enrollment,
        access_request=access_request,
        lessons=lessons,
        selected_lesson=selected_lesson,
    )


@courses_bp.route("/<int:course_id>/certificate")
@login_required
def download_certificate(course_id):
    uid = session["user_id"]
    course = fetchone("SELECT id, title, title_ar, language FROM courses WHERE id=?", (course_id,))
    if not course:
        flash("Course not found.", "danger")
        return redirect(url_for("courses.index"))

    enrollment = fetchone(
        "SELECT is_completed, completed_at FROM enrollments WHERE user_id=? AND course_id=?",
        (uid, course_id),
    )
    if not enrollment or not enrollment.get("is_completed"):
        flash("Complete the course to unlock your certificate.", "warning")
        return redirect(url_for("courses.detail", course_id=course_id))

    user = fetchone("SELECT full_name, username FROM users WHERE id=?", (uid,)) or {}
    student_name = user.get("full_name") or user.get("username") or "Student"
    language = _resolve_course_language(course)
    course_title = _resolve_course_title_for_certificate(course, language)
    completed_on = _format_completion_date(enrollment.get("completed_at"), language)
    qr_payload = f"Academic Kechafa Certificate|student={student_name}|course={course_title}|completed_on={completed_on}|course_id={course_id}|user_id={uid}"
    try:
        pdf_data = _build_course_certificate_pdf(student_name, course_title, completed_on, language, qr_payload)
    except RuntimeError:
        flash("Certificate generation is unavailable until the new PDF dependencies are installed.", "danger")
        return redirect(url_for("courses.detail", course_id=course_id))

    filename = secure_filename(f"{student_name}_{course_title}_certificate.pdf") or f"course_certificate_{course_id}.pdf"
    response = make_response(pdf_data)
    response.headers["Content-Type"] = "application/pdf"
    response.headers["Content-Disposition"] = f'attachment; filename="{filename}"'
    return response


@courses_bp.route("/<int:course_id>/enroll", methods=["POST"])
@login_required
def enroll(course_id):
    course = fetchone("SELECT * FROM courses WHERE id=?", (course_id,))
    if not course:
        return redirect(url_for("courses.index"))
    flash("Course access is granted by admin or instructor.", "warning")
    return redirect(url_for("courses.detail", course_id=course_id))


@courses_bp.route("/<int:course_id>/request-access", methods=["POST"])
@login_required
def request_access(course_id):
    uid = session["user_id"]
    user = fetchone("SELECT id, username, full_name, role FROM users WHERE id=?", (uid,))
    course = fetchone("SELECT * FROM courses WHERE id=?", (course_id,))
    if not course:
        flash("Course not found.", "danger")
        return redirect(url_for("courses.index"))

    if not user or user.get("role") != "scout":
        flash("Only scouts can request course access.", "warning")
        return redirect(url_for("courses.detail", course_id=course_id))

    if fetchone("SELECT id FROM enrollments WHERE user_id=? AND course_id=?", (uid, course_id)):
        flash("You already have access to this course.", "info")
        return redirect(url_for("courses.detail", course_id=course_id))

    latest_request = _latest_course_access_request(uid, course_id)
    if latest_request and latest_request.get("status") == "pending":
        flash("Your access request is already pending.", "info")
        return redirect(url_for("courses.detail", course_id=course_id))

    request_id = execute(
        """
        INSERT INTO course_access_requests (requester_id, course_id, status, note)
        VALUES (?, ?, 'pending', ?)
        """,
        (uid, course_id, request.form.get("note", "").strip() or None),
    )

    reviewers = fetchall(
        "SELECT id, role, username FROM users WHERE is_active=1 AND (role='admin' OR username='lead_instructor')"
    )
    for reviewer in reviewers:
        notification_service.notify_course_access_request(
            admin_id=reviewer["id"],
            requester=user,
            course=course,
            request_id=request_id,
        )

    flash("Your access request has been sent to the admin.", "success")
    return redirect(url_for("courses.detail", course_id=course_id))


@courses_bp.route("/<int:course_id>/lesson/<int:video_id>", methods=["GET", "POST"])
@login_required
def lesson_detail(course_id, video_id):
    uid = session["user_id"]
    notification_service.mark_related_as_read(uid, entity_type="course", entity_id=course_id)
    notification_service.mark_related_as_read(uid, entity_type="lesson", entity_id=video_id)
    course = fetchone(
        "SELECT c.*, cc.name as category_name, cc.emoji as category_emoji, u.full_name, u.avatar_url as uavatar, u.level_rank "
        "FROM courses c JOIN users u ON c.instructor_id=u.id "
        "LEFT JOIN course_categories cc ON cc.slug = c.category "
        "WHERE c.id=?",
        (course_id,),
    )
    if not course:
        flash("Course not found.", "danger")
        return redirect(url_for("courses.index"))

    role = _current_user_role()
    can_manage = _can_manage_course(course, uid, role)
    enrollment = fetchone("SELECT * FROM enrollments WHERE user_id=? AND course_id=?", (uid, course_id))
    if not enrollment and not can_manage:
        flash("Enroll in the course to access this lesson.", "warning")
        return redirect(url_for("courses.detail", course_id=course_id))

    lessons = fetchall(
        "SELECT * FROM videos WHERE course_id=? AND video_type='lesson' "
        + ("" if can_manage else "AND is_published=1 ")
        + "ORDER BY order_index ASC",
        (course_id,),
    )
    lesson = next((item for item in lessons if item["id"] == video_id), None)
    if not lesson:
        flash("Lesson not found.", "danger")
        return redirect(url_for("courses.detail", course_id=course_id))

    completed_rows = fetchall("SELECT video_id FROM lesson_completions WHERE user_id=? AND course_id=?", (uid, course_id))
    completed_ids = {row["video_id"] for row in completed_rows}
    lesson_completed = video_id in completed_ids

    def dur_fmt(seconds):
        if not seconds:
            return "-"
        minutes, sec = divmod(int(seconds), 60)
        return f"{minutes}:{sec:02d}"

    for index, item in enumerate(lessons, start=1):
        item["duration_display"] = dur_fmt(item.get("duration_secs"))
        item["position"] = index
        item["is_completed"] = item["id"] in completed_ids

    lesson["duration_display"] = dur_fmt(lesson.get("duration_secs"))
    lesson.update(_lesson_player_meta(lesson.get("video_url")))
    lesson_index = next((idx for idx, item in enumerate(lessons) if item["id"] == video_id), 0)
    previous_lesson = lessons[lesson_index - 1] if lesson_index > 0 else None
    next_lesson = lessons[lesson_index + 1] if lesson_index + 1 < len(lessons) else None

    quiz_questions = _fetch_lesson_quiz_questions(video_id, lesson)
    for index, question in enumerate(quiz_questions, start=1):
        question["position"] = index
        question["field_name"] = f"quiz_answer_{question['id'] or index}"
        question["options"] = [
            (key, text) for key, text in [
                ("a", question.get("quiz_option_a")),
                ("b", question.get("quiz_option_b")),
                ("c", question.get("quiz_option_c")),
                ("d", question.get("quiz_option_d")),
            ] if text
        ]

    has_quiz = bool(quiz_questions)
    selected_answers: dict[str, str] = {}
    quiz_feedback = None
    quiz_feedback_type = "success"

    if request.method == "POST":
        action = request.form.get("action", "complete")
        if action == "submit_quiz" and has_quiz:
            answer_payload: dict[str, str] = {}
            missing_answer = False
            has_wrong_answer = False
            correct_answers = 0

            for question in quiz_questions:
                selected_answer = request.form.get(question["field_name"], "").strip().lower()
                selected_answers[question["field_name"]] = selected_answer
                answer_payload[str(question["id"] or question["position"])] = selected_answer
                valid_options = {key for key, _ in question["options"]}
                if selected_answer not in valid_options:
                    missing_answer = True
                    continue
                if selected_answer != question.get("quiz_correct_option"):
                    has_wrong_answer = True
                    continue
                correct_answers += 1

            if missing_answer:
                quiz_feedback = "Answer every quiz question before submitting."
                quiz_feedback_type = "danger"
            elif has_wrong_answer:
                quiz_feedback = "One or more answers are not correct yet. Try again."
                quiz_feedback_type = "danger"
            else:
                result = _mark_lesson_complete(
                    uid,
                    course_id,
                    video_id,
                    json.dumps(answer_payload, sort_keys=True),
                    correct_answers / max(1, len(quiz_questions)),
                )
                if result.get("reason") == "not_enrolled":
                    flash("Enroll in the course to track progress.", "warning")
                    return redirect(url_for("courses.detail", course_id=course_id))
                lesson_completed = True
                enrollment = fetchone("SELECT * FROM enrollments WHERE user_id=? AND course_id=?", (uid, course_id))
                quiz_feedback = "All answers are correct. Lesson completed."
                if result.get("already_completed"):
                    quiz_feedback = "All answers are correct. This lesson was already completed."
                elif result.get("course_completed"):
                    quiz_feedback = "All answers are correct. Lesson completed and the whole course is now complete."
                quiz_feedback_type = "success"
        elif action == "complete":
            result = _mark_lesson_complete(uid, course_id, video_id)
            if result.get("reason") == "not_enrolled":
                flash("Enroll in the course to track progress.", "warning")
                return redirect(url_for("courses.detail", course_id=course_id))
            lesson_completed = True
            enrollment = fetchone("SELECT * FROM enrollments WHERE user_id=? AND course_id=?", (uid, course_id))
            flash("Lesson completed.", "success" if not result.get("already_completed") else "info")
            return redirect(url_for("courses.lesson_detail", course_id=course_id, video_id=video_id))

    return render_template(
        "courses/lesson.html",
        course=course,
        lesson=lesson,
        lessons=lessons,
        enrollment=enrollment,
        can_manage=can_manage,
        lesson_completed=lesson_completed,
        has_quiz=has_quiz,
        quiz_questions=quiz_questions,
        selected_answers=selected_answers,
        quiz_feedback=quiz_feedback,
        quiz_feedback_type=quiz_feedback_type,
        previous_lesson=previous_lesson,
        next_lesson=next_lesson,
    )


@courses_bp.route("/<int:course_id>/lesson/<int:video_id>/complete", methods=["POST"])
@login_required
def complete_lesson(course_id, video_id):
    uid = session["user_id"]
    result = _mark_lesson_complete(uid, course_id, video_id)
    if result.get("reason") == "not_enrolled":
        return redirect(url_for("courses.detail", course_id=course_id))
    if result.get("already_completed"):
        flash("Lesson already completed.", "info")
    elif result.get("course_completed"):
        flash("Course completed! XP awarded!", "success")
    else:
        flash("Lesson completed.", "success")
    return redirect(url_for("courses.lesson_detail", course_id=course_id, video_id=video_id))
